### ISSUE TITLE
examples should auto be deployed at mock.open-rpc.org

### ISSUE THREAD

**Issue by shanejonas** [open-rpc/mock-server#354]
**Describe the bug**
we have some docs that link to: https://inspector.open-rpc.org/?url=https://mock.open-rpc.org/petstore-1.0.0&?request[jsonrpc]=2.0&request[method]=list_pets&request[id]=0

**Additional Details**
We need an automated way to deploy the examples to mock.open-rpc.org, currently remembering to do it by hand after deploying isn't working, and we have a couple README's relying on it for examples (like inspector)

**Comment by hholst80** [comment]
May I suggest a simple solution to this?

Use docker-compose.yml format to describe one service per example.  Expose the mock server (running Docker Engine) to the CI/CD pipeline such that docker [command] and docker-compose [command] can be executed on the mock server.  When the openrpc.json schemas *or* MockServer are updated the CI/CD pipeline will trigger a rebuild of the container and redeploy it (if changed).

Example GitHub actions:

```
name: build-test-deploy

on:
  push:
    branches:
      - master

env:
  DOCKER_TLS_VERIFY: '1'
  DOCKER_CERT_PATH: '.certs/connecticut'  # Using TLS certs in git not a good idea for public repo!
  DOCKER_HOST: 'tcp://docker.example.net:2376'

jobs:
  build-test:
    runs-on: ubuntu-20.04
    env:
      COMPOSE_FILE: 'docker-compose.test.yaml'
      COMPOSE_PROJECT_NAME: 'test'
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose version
      - run: docker-compose build --pull
  test:
    runs-on: ubuntu-20.04
    needs: build-test
    env:
      COMPOSE_FILE: 'docker-compose.test.yaml'
      COMPOSE_PROJECT_NAME: 'test'
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose version
#     - run: docker-compose run --rm test1
#     - run: docker-compose run --rm ...
  build-prod:
    runs-on: ubuntu-20.04
    needs: test
    env:
      COMPOSE_FILE: 'docker-compose.prod.yaml'
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose version
      - run: docker-compose build --pull
  deploy:
    runs-on: ubuntu-20.04
    needs: build-prod
    env:
      COMPOSE_FILE: 'docker-compose.prod.yaml'
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose version
      - run: docker-compose up -d --remove-orphans
```
